### ISSUE TITLE
Wafer fails with latest django-registration-redux

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#113]
From the docs of django-registration-redux 1.2:

"The templates in django-registration-redux assume you have a base.html template in your project’s template directory. This base template should include a title block and a content block. Other than that, every template needed is included. "

wafer's current base.html template lives in templates/wafer, which is not where django-registration-redux is looking for it. It also doesn't have a title block

**Comment by drnlm** [comment]
We can probably address this by providing a custom registration_base.html template, which provides the appropriate title and content blocks

**Comment by stefanor** [comment]
I cherry-picked 89b54ef274a3d0f4ddbedb18a3671043665b4235 into master, fixing this.
