### ISSUE TITLE
Consider adding a Pentabarf XML schedule export for use with Giggity

### ISSUE THREAD

**Issue by hodgestar** [CTPUG/wafer#114]
* Example of Pentabarf format: https://summit.debconf.org/debconf15.xml
* Pentabarf documentation: http://pentabarf.org/ (such as it is)
* Giggity Android app: https://play.google.com/store/apps/details?id=net.gaast.giggity

**Comment by hodgestar** [comment]
Alternatively we could try for xCal or iCal.

**Comment by drnlm** [comment]
Presumably this needs to accessible to arbitary users to be useful.

Would this be something we want dynamically generated when the schedule updates, or is it enough to have a management command to generate it, with the associated risks of being out of sync?

**Comment by drnlm** [comment]
xCal/iCal is probably more generically useful, but converting between pentabarf and xCal should be a problem other people have already solved.

**Comment by drnlm** [comment]
issue-114-feature-pentabarf-xml-support @7c8c6f5867f9b4a66e491fdac44d99722589eba6 supports enough that I can push the current draft schedule into giggity and it more or less looks correct.

This suffers from creating the schema by reading examples and trying stuff - if there are other tools that can import pentabarf's format, we should definitely test with them to uncover issues.

We will need to do something better about timezones, and the talks support has seen very little testing, but this is enough for people to play with it

**Comment by hodgestar** [comment]
We now have basic pentabarf support. We can open more specific issues for any enhancements we need.

**Comment by hodgestar** [comment]
P.S. Tx @drnlm
