### ISSUE TITLE
Add editing tracking to pages and abstracts

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#116]
(filed so the idea doesn't get lost in the shuffle)

Providing more detailed information about when something was last edited and by who would be helpful for both pages and abstracts.

Balistic on #ctpug recommended looking at django-reversion, which looks pretty nifty, and would also allow adding some more useful features

**Comment by madduck** [comment]
I am also interested in versioning, but am investigating means to store content externally: #150

**Comment by hodgestar** [comment]
Should adding django-reversion be included in the wafer 0.4 milestone?

**Comment by drnlm** [comment]
I think it should be part of the next milestone - it's a feature that's worth adding sooner rather than later.

**Comment by drnlm** [comment]
Partially addressed by #194 , but that only exposes the history in the admin interface. For pages, I think we also want something that visible to the page editors.

**Comment by drnlm** [comment]
With #286 merged, I'm closing this.
