### ISSUE TITLE
Add organizer note space for talk abstracts

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#117]
The talks current provide notes which are editable by the speaker and the conference organisers, which is useful for tracking various details, but being editable by the speaker, it's not ideal for to use for notes by the talk organiser about the talk.

Talks should have an extra "organiser notes" field which isn't editable by the speaker.

There may actually be a case for 2 such fields - one visible to the speaker and one for private notes only visible by the  talk committee (when there's a committee) and any mentors.

**Comment by madduck** [comment]
Adding the field is trivial and done in https://github.com/madduck/wafer/commit/c65a299be3529fd0ae76fc35f088e476dbcef0ed. The field isn't visible to the user, but it is exposed in the admin interface.

However, I am not yet far enough into the code that i know how to tie it down security-wise, and I have not looked at giving access to talk admins or mentors. I'd love to be shoved in the right direction here.

If I add 'private_notes' to 'list_editable' in wafer.talks.admin.TalkAdmin, I get an error:
    <class 'wafer.talks.admin.TalkAdmin'>: (admin.E122) The value of 'list_editable[1]' refers to 'private_notes', which is not an attribute of 'talks.Talk'.
even though the field is obviously an attribute of Talk and the migration has been applied.

**Comment by madduck** [comment]
What did you intend for the second field, i.e. a notes space visisble to both, submitter and the editors? Is this some sort of "chat" where the two can go back and forth? Why not just use the existing notes field? I also wonder if that's needed (submitters won't get notified…) or whether email will be used anyway.

**Comment by drnlm** [comment]
The current notes field is intended for the speaker to add information that isn't relevant to the abstract

"I want to connect to the speaker system to play some videos", "This talk will be simalar to the talk I gave at X, but I'm going to spend less time on Y" and that sort of thing.

The organiser notes is intended for a reviewer to add notes about the submission , for the benefit of other reviewers - "I think the proposal is unclear, so I've asked for more information about X", "This talk is very similar to Z's proposal, so we should only accept one of them". While this can be handled by email, it is useful to keep relevant infromation together. This should generally not be exposed to the talk author, since it may leak information. 

There is a use case for a notes field that is only editable by the organisers and visible to the author for review comments. These should not be editable by the talk submitter for auditability, but this is only really useful if the talk review work-flow is largely web-driven.

**Comment by madduck** [comment]
Thanks for the explanations, @drnml.

I think the private notes field makes sense, as it gives the organisers a central place to keep shared notes, at least in poor-man's fashion. It's also voluntary, so we could still use a Wiki or Git or any other way we chose.

But I am not convinced about the "whiteboard field" that the organisers can use to leave notes for the submitter. For one, I do believe that this sort of stuff naturally happens over email anyway. And if we added it, then we'd also need to have some form of notification system to alert the submitter of new notes.

However, I'd love to know how one would approach this. I understand the model layer, and the view/template aspect of it, but I am unsure about the best way of tying this in with `django.contrib.auth`'s groups. Would it really mostly be custom code checking group membership and then hiding the field from view, or making it read-only under certain conditions?

I've developed a lot of Zope, which has very granular, object-level permissions. With Zope, we never settled for just hiding a field, but wetold Zope to lock it down for us. Is Django's view layer the only interface the users have to the database and therefore it's enough to just control access there?

**Comment by stefanor** [comment]
> I've developed a lot of Zope, which has very granular, object-level permissions

That explains some of your questions. I was tempted to say "Django is not Zope" a few times :P

Nope, you don't get permissions that fine-grained.

**Comment by madduck** [comment]
FYI, apparently django-guardian is the project to use if you wanted/ needed row-level access control.

For wafer I think we don't need it though. It just took me a while to wrap my head around it.

**Comment by madduck** [comment]
I think this issue can now be closed.
