### ISSUE TITLE
pentabarf.xml missing stuff

### ISSUE THREAD

**Issue by CarlFK** [CTPUG/wafer#119]
https://za.pycon.org/schedule/pentabarf.xml

```
<conf_url>/talks/14/</conf_url>  
```
should be the full url

missing:
twitter_id
released  (There is no field in the model, so just hard code it to True)

**Comment by CarlFK** [comment]
no contact for 2nd speaker:
```
<event id="31">
<persons>
<person contact="..." id="53">Tsatsi Mahase</person>
<person id="54">Bukiwe Tsoeu</person>
```

**Comment by drnlm** [comment]
The behaviour of <conf_url></conf_url> matches that of summit's pentabarf export.

Neither Giggity nor confclerk appear to use it, so we can change it without breaking those, but I'm still reluctanct to deviate too much from how other conferences produce pentabarf files.

**Comment by hodgestar** [comment]
I'm not sure summit's implementation should be viewed as canonical and it
does seem odd to list contacts for some speakers and not others if the data
is available.

There is the concept of "corresponding author" but not sure how applicable
it is here / now.

**Comment by CarlFK** [comment]
I have no problem with switching to another attribute name, like full_conf_url 
it is better than having code like this:

```                    # event['conf_url'] = 'https://summit.debconf.org' + row.find('conf_url').text
                    event['conf_url'] =   'https://za.pycon.org' + row.find('conf_url').text
```

**Comment by hodgestar** [comment]
@carl -- shouldn't your code be something like
`urllib.basejoin(pentabarf_url, row.find('conf_url').text)`? That would
work for relative and absolute URLs and for both summit and pyconza.

**Comment by drnlm** [comment]
I've add a 'full_conf_url' tag to the pentabarf.xml file which has the complete url now.

I've also added the twitter url for those persons that have that set as an attribute visible to authorized users.

**Comment by hodgestar** [comment]
This will be complete when #122 lands.

**Comment by hodgestar** [comment]
#122 has landed.
