### ISSUE TITLE
Add speakers page.

### ISSUE THREAD

**Issue by hodgestar** [CTPUG/wafer#126]
Would be nice to have a page that displayed a list of speakers for accepted talks in alphabetical order alongside their avatars. It could list their talks in small print beneath them with links to the relevant talk pages.

**Comment by madduck** [comment]
When I read tghe issue title, I thought of a speaker dashboard, e.g. a page that tells the speaker (or any attendee really if we allow people to preregister attendance to events at some point) their personal schedule…

**Comment by hodgestar** [comment]
Addressed by #164.
