### ISSUE TITLE
Include talk type in the schedule

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#127]
From IRC

**Hodgestar**: drnlm: How do you feel about adding having the talk type on the schedule page somehow? Perhaps as an additional class on the appropriate td>
**tumbleweed**: sounds useful

Obvious implementation questions:
 * Should we restrict the Talk Types to things that can easily be turned into attribute values? Or just rely on good stanitization?
 * Do we need a type for pages in the schedule?

**Comment by madduck** [comment]
Is it easy with Django to factor this into a template that we could provide by default, but which subprojects could easily override and thereby influence the way events are rendered in each schedule cell?

**Comment by stefanor** [comment]
@madduck: Yes it is. But adding the class to the `td`s is probably sufficient for almost every use-case.

**Comment by madduck** [comment]
Indeed, so either we need a TalkType → CSS class mapping, or a function ("slugify"?), or we add the CSS class to the event type (Summit does this, and also allows an icon for each TalkType).

**Comment by drnlm** [comment]
With #268 merged, is there anything more we need to do on this issue?

**Comment by hodgestar** [comment]
Not that I can think of.
