### ISSUE TITLE
Key-value store for custom properties

### ISSUE THREAD

**Issue by madduck** [CTPUG/wafer#147]
Over the years at DebConf, we kept adding fields and growing the database. Recently, the idea came up to offer a flexible key-value store instead, such that the database itself does not need to be touched and more can be done in the middleware or in scripts.

Think of this as "user tags" and it could be anything from the admins creating keys for people who need them, to every attendee having the ability to associate any data with any object (page, attendee, talk, etc.).

A first braindump of the idea is here:
https://wiki.debconf.org/wiki/Wafer/KeyValueStore

This is high-priority for DebConf, I'd say, and I am very motivated to work on it. Posting the issue here as an invitation for feedback and warnings etc.

**Comment by stefanor** [comment]
@madduck: I see you have a branch. What's the status of it? And, does it have to use an incompatible license?

**Comment by madduck** [comment]
The status of the branch is: theoretically ready, but the way I've done it means that `admin.py` integration won't be able to reuse code from `django.contrib.contenttypes` and I could not be bothered to hack that. Instead, I've written https://groups.google.com/forum/#!searchin/django-developers/krafft/django-developers/jx-14OddSqA/-ssU44MaCQAJ (and found https://groups.google.com/forum/#!searchin/django-users/genericforeignkey/django-users/4cMifVb7iDM/0_BS08RFtS0J) and was investigating trying to write `ExtendedGenericForeignKey`.

I don't see myself working on this until 2015-12-26 as we're now with family for the next few days. However, neither API nor database are expected to change as a result of this, so it should be possible to just work off what we have for now and we can later change the guts. I think.

The licence is just my default. It can be anything else. I don't see any reason why we should forego copyleft though. But I am not going to dig in my hoofs on this.

**Comment by madduck** [comment]
I've reworked the code as suggested on django-developers, now using `IndirectGenericForeignKey`. This made the code more robust and more usable. It's still missing some tests and docs, but I'll get onto that (and the other TODO items) as soon as I know that this is the right track.

I've also updated the licence on all code to be explicitly the same licence as Wafer.
