### ISSUE TITLE
Ability to lock pages (external data import)

### ISSUE THREAD

**Issue by madduck** [CTPUG/wafer#150]
Traditionally, DebConf kept web content in version control and some of us want to keep it that way, rather than requiring users to edit the webpages through the web and losing versioning along the way.

One idea that came up recently was to load data from Git into Django with a `post-receive` hook. To prevent users' edits through the web from being overwritten, editing should thus be disabled. It could be done globally (remove the "change_page" permission), or on a per-page basis, but the latter requires a "locked" field in the database (since Django permissions are per-task, not per-object).

This is low-priority but might be something I'll just hack up in a night as the actual Git export seems trivial, and I need similar functionality for another (paid) project anyway.

**Comment by hodgestar** [comment]
Is the idea that the Git repository would store JSON objects that represent the entire page model contents, or just the page markdown?

**Comment by hodgestar** [comment]
I'm a bit against completely locking out edits from Django admin (given that sometimes admins just need to fix things right now) but perhaps we could add an "externally maintained" flag that warns people that their edits might be overwritten by some external system? Perhaps the first implementation should just rely on updating page content via the API (#181) and we can then fiddle with the details once we have a sense of what the publishing workflow from Git looks like?

**Comment by madduck** [comment]
@hodgestar: Git would hold just the page markdown, really. There are metadata that might need to be encoded in the file (e.g. title), but I wouldn't use JSON for that.

The Git workflow is simple: keep the content outside of the database as using Git allows for better collaboration, asynchronous workflow, analysis (diff, blame, etc.), and trivial reuse of content. Since wafer instances are one-per-conference, but a lot of the static text we write for the conference site essentially comes from somewhere else or will be used again in the future, shoving it in and out of a database for each year seems wrong.

At least for DebConf, I see a three stage process: (1.) the wiki collects pretty much everything in quick-n-dirty fashion; (2.) certain stuff from there gets pulled into Git, amassing a resource usable across the years; and (3.) each wafer instance has access to the static text in Git and mainly adds all the dynamic handling around it. IMHO, Django and through-the-web-editing are great for object-oriented/model-based editing workflows, but simple text is much better handled using proper editors and content trackers.
