### ISSUE TITLE
Specify post-schedule-item break time

### ISSUE THREAD

**Issue by madduck** [CTPUG/wafer#151]
Having the end time of one slot be the beginning of another slot makes it difficult to cater for e.g. 5 minute breaks after talks to allow people to change rooms, unless slots are just 5 minutes long and 45 minute events span 9 of them and the next slot the remains free.

Maybe another approach would be to have schedule items differentiate between duration of the slot(s) they need, and the duration of the content?

**Comment by drnlm** [comment]
We can already do this by having slots with varying lengths - i.e. a 30 minute talk slot followed by a 15 minute Q & A slot (pointed at a suitable page).
