### ISSUE TITLE
Schedule Editor should report validation errors

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#158]
The drag-n-drop schedule should report any validation errors that apply to the current schedule

**Comment by zoidbergwill** [comment]
I added a simple effort at this [here](https://github.com/CTPUG/wafer/pull/245/commits/26b77fa54a7269e6d7aab4b5e7e7c6574a55595d), however it should probably be its own PR.

**Comment by drnlm** [comment]
Current status - the schedule editor displays validation errors on page load, but doesn't dynamically update them.

This is more of an issue now, since the addition of speaker clash checks makes it much easier to introduce errors while working on the schedule and the lack of feedback (on either creating or resolving such an error) is more noticable.
