### ISSUE TITLE
Please parametrise the template namespace

### ISSUE THREAD

**Issue by madduck** [CTPUG/wafer#168]
The view templates of the various wafer apps hard-code "wafer/base.html" as the base template, which means that the only way to customise the layout and add additional stylesheets seems to be to prepend an override to `TEMPLATE_DIRS`.

If the namespace could be parametrised to e.g. "{{ WAFER_TEMPLATE_NS }}/base.html", then sites could provide their own base.html — which could then well extend wafer/base.html.

**Comment by hodgestar** [comment]
What is wrong with prepending to `TEMPLATE_DIRS`?

**Comment by madduck** [comment]
Hi @hodgestar. Fundamentally, prepending to `TEMPLATE_DIRS` works, but it means you have to fork the entire `base.html` template and provide `wafer/base.html`. If all you want to do is add a style sheet to `extra_head` and override the `content` block, then you cannot extend the other (upstream) `wafer/base.html` that comes later in `TEMPLATE_DIRS` due to having to override the whole namespace.

**Comment by drnlm** [comment]
wafer's base template is intentionally minimalist, and the intention is that conferences will override this with their own version of it with the required style sheets. I'm not seeing the advantage of adding complexity to allow people to avoid this in the few cases where conferences will not be providing their own base.html. 

What is gained by not overriding base.html ?

**Comment by madduck** [comment]
@drnlm If the intention is that everyone needs to be overriding the base template anyway, then my suggestion is pointless. I suppose I always try to take a "make minimal changes" approach to frameworks, to maximise code reuse.
