### ISSUE TITLE
Limiting the list of associated authors

### ISSUE THREAD

**Issue by madduck** [CTPUG/wafer#169]
It's great that Wafer lets me add additional authors to a talk. However, this means that currently anyone submitting a talk has access to the list of registered users (and no way to specify co-authors not yet registered). While the latter is only a nuisance and requires later editing, the former has been considered a privacy problem in the DebConf context.

Would you entertain an alternative approach? This could be two-fold:

1. Provide a text-field allowing the free-form addition of additional authors. Entries here could be matched against the username of the Users table to give access to augmented information (e.g. show the full name), but could also just be displayed as-is in case there is no match. This can be abused and might yield orphan data, but the information is purely informational anyway.

2. Allow users to "claim talks", causing them to show up in the list of possible authors for a talk, from which then the author can select to confirm co-authorship. This is a bit more complex, but IMHO the right way to do things.

**Comment by stefanor** [comment]
There's an even simpler solution, which solves #174 too. Make talks have one speaker, and an optional text field that overrides the speaker name. Downside would be that the talk doesn't show up on everyone's profile pages. Upside: lots of simplification.

Your Option 1 works for me, too.

**Comment by drnlm** [comment]
For conferences like PyCon ZA, it's important that the talk organisers are able to verify that speakers have purchased tickets, provided contact information and so forth. This is why we require that any speaker must be registered on the site, so this information can be easily checked. Any solution that makes this harder risks breaking wafer for that use case.

**Comment by stefanor** [comment]
@drnlm: I wasn't considering that, yeah. I think that is relevant for other conferences too. DebConf would presumably match speakers with confirmed attendance.

That means that authors has to remain a 1:many map.

I think it's fair to require a talk submitter to know the wafer usernames of his co-presenters.

**Comment by hodgestar** [comment]
@stefanor & I discussed this quite a bit. Speaker profiles need to be publicly visible. so we might be able to solve this by having an "internally public" flag on user profiles that allows users to opt-in to being visible to other attendees in things like speaker selection lists.

For some conferences "internally public" might be opt-out (e.g. PyConZA), for others it might be opt-in (e.g. "DebConf").
