### ISSUE TITLE
talks: Notes section is not visible to talk mentors

### ISSUE THREAD

**Issue by madduck** [CTPUG/wafer#170]
Contrary to the documentation (https://github.com/CTPUG/wafer/blob/master/docs/talks.rst#submitting-talks), the notes field is actually not visible to talk mentors, and neither to the submitter. In fact, it isn't even mentioned in the talks template.

I propose to create new permissions ("talks.view_notes" and "talks.edit_notes") instead of chaining this onto the existing permissions.

I could fix this alongside #117.

**Comment by stefanor** [comment]
Don't think we need `talks.edit_notes`. Only the submitter should be editing this, and django permissions won't cover that.
