### ISSUE TITLE
Make corresponding_author the submitter

### ISSUE THREAD

**Issue by madduck** [CTPUG/wafer#174]
[forking an issue from discussion in #172; cc. @stefanor]

The corresponding author is really the submitter and not even necessarily a speaker at an event (see #172). I think it'd make things clearer if we renamed the field. It's good to be able to submit events for other speakers, that's for sure (although maybe this should be restricted to a specific group of people).

As it's currently being used in the schedule view to put a sole name under an event (where space is tight), we'd have to find another source. I would suggest to pick the author with the lowest ID in the `talks_talk_authors` relation as the primary author. That way, the result is only really undefined if a talk is created with several authors right from the start, whereas it'll be well-defined if authors get added later. Then I'd use an algorithm such as the following for the schedule display:

    schedule_author = authors[0]
    if len(authors) == 2:
        schedule_author += " & %s" % authors[1]
    elseif len(authors) > 2:
        schedule_author += ", et al."

then put the entire list of authors into the mouseover text, as well as the talk details page.

For cases where this doesn't yield the desired result, we could provide an override box that will be displayed in the schedule instead. This would allow us to have talks by e.g. "Neil McGovern, DPL", as well as talks in the schedule by "The Release Team", if that is desired on the individual level.

**Comment by hodgestar** [comment]
I `corresponding_author` covers the intent of that field pretty well. `authors` is bit vague and possibly `speakers` would be a better name. Both definitely need help text. I'll add that and then people can decide whether the help text is correct and whether field renaming is needed.

**Comment by hodgestar** [comment]
I vote for closing this issue here and not renaming fields. Any objections?
