### ISSUE TITLE
Fix Python 3 regressions

### ISSUE THREAD

**Issue by zoidbergwill** [CTPUG/wafer#247]
There are a couple places we use `.iteritems()` on dictionaries in the code:

https://github.com/CTPUG/wafer/blob/a120735a20ff67c6f863c6ca89cc6dfd9b0fc16e/wafer/schedule/templates/admin/scheduleitem_list.html#L14

https://github.com/CTPUG/wafer/blob/a120735a20ff67c6f863c6ca89cc6dfd9b0fc16e/wafer/schedule/templates/admin/scheduleitem_list.html#L50

https://github.com/CTPUG/wafer/blob/a120735a20ff67c6f863c6ca89cc6dfd9b0fc16e/wafer/registration/sso.py#L69

https://github.com/CTPUG/wafer/blob/2dbf7020ef0c7f7d7541b68b1423fcbe5cb8ad8f/wafer/users/views.py#L173

Since `six` is bundled with Django, we can probably use that instead of using `.items()` across the board because of the performance issues on Python 2.

I'm not sure what the simplest solution for the `iteritems` uses in the templates though.

**Comment by drnlm** [comment]
The non-template cases here are both only called during user registration. I don't think either is likely to be enough of a bottleneck that the difference between using dict.items and dict.iteritems will actually matter.

The use in the schedule admin template is iterating over the error results - those should hopefully be small or empty in most cases, so the distinction between items and iteritems shouldn't be significant there either.
