### ISSUE TITLE
Penta XML broken for Giggity when schedule isn't public

### ISSUE THREAD

**Issue by stefanor** [CTPUG/wafer#253]
![giggity](https://cloud.githubusercontent.com/assets/442117/15864087/e44c23a8-2cd5-11e6-9b08-983656672963.png)

**Comment by drnlm** [comment]
I'm pretty sure this because we don't specify any 'day' elements in that case. I don't know that's there's a good fix here.

Rendering less of the pentabarf file (or nothing) will cause giggity to fail with a 'file format not recognised' error, which might be better, although still rather misleading. An alternative is to render some fake data in the far future with a 'not yet published' event. although giggity's willingness to cache results for long periods of time makes that unattractive in other ways.

**Comment by Wilm0r** [comment]
Oops. Hello, Giggity author here.

Note that it should only be caching things for up to 24h. From my experiences with crappy conference WiFi I feel like this is a safe choice, though of course it can also suck with last-min changes in mind.

Anyway ... ok, Giggity is not exactly meant for empty schedules like that, no. Is this a hand-generated one, or is this what frab/Pentabarf generate when there are no events created yet? If I can make some reasonable assumptions to tell empty files apart from corrupted files I can probably handle this a little more gracefully.

**Comment by stefanor** [comment]
> Is this a hand-generated one, or is this what frab/Pentabarf generate when there are no events created yet?

The latter.

**Comment by Wilm0r** [comment]
Ack. I'll add handling for that then, will drop a comment when that's done.

**Comment by stefanor** [comment]
What `wafer` (this github project) generates when there are no events.

**Comment by drnlm** [comment]
Given that the pentabarf xml format isn't that well specified, we can add more informantion to our  empty schedule file if it would make it easier for Giggity to handle.

**Comment by Wilm0r** [comment]
I think it'd get pretty confused by an empty file either way.

Indeed the format is poorly specified so I'm just adapting it to the now three programs I know that generate it.

**Comment by Wilm0r** [comment]
This should look better in https://github.com/Wilm0r/giggity/commit/47832e02f1add04773ad6931eb18dd80e95ca4b7

Luckily the exception is thrown at finalisation time so fairly easy to just check, regardless of the format, whether any items were actually loaded.

Just let me know if there's anything else I could do for better integration with Wafer. (Also, good to know about more Pentabarf-style generators!)

**Comment by hodgestar** [comment]
@Wilm0r Thanks! :)
