### ISSUE TITLE
Cancelled talk state

### ISSUE THREAD

**Issue by stefanor** [CTPUG/wafer#265]
So we can tell the difference between talks the content team rejected, and talks where the speaker withdrew.

**Comment by drnlm** [comment]
#267 has the basic minimum basic support for this.

Do we want to allow authors to cancel their own talks? This sounds useful, but may it may be better to require admin intervention to ensure cancelled talks are noticed.

Using 'label-danger' for both rejected and cancelled talks makes them a bit hard to distinguish in the talks list, but I'm not sure which bootstrap level is a better fit. Maybe we should change 'pending' to something other than 'label-warning' (perhaps 'label-info'?), and use the warning level for cancelled instead?

**Comment by hodgestar** [comment]
I would be in favor of requiring an admin to cancel a talk, especially if it's already been accepted or scheduled.

Happy to change `pending` to `label-info` and using `label-warning` for `cancelled`.

**Comment by drnlm** [comment]
Closed with #257. Further tweaks to this should be separate issues.

**Comment by stefanor** [comment]
I'm late to the party here, but:

> Do we want to allow authors to cancel their own talks? This sounds useful, but may it may be better to require admin intervention to ensure cancelled talks are noticed.

That makes sense. But we probably need something in the template to tell the submitter how to go about cancelling their talk.
