### ISSUE TITLE
Add optional speakers' page (a page showing speaker's bios).

### ISSUE THREAD

**Issue by hodgestar** [CTPUG/wafer#275]
Something like: http://scaleconf.org/speakers/

**Comment by zoidbergwill** [comment]
So we have [`talks/speakers/`](https://github.com/CTPUG/wafer/blob/master/wafer/talks/urls.py#L22) which I added [here](https://github.com/CTPUG/wafer/commit/94445bd75c95405cce70e0ddceb82e3d938abd60).

We could add more info to that page?

**Comment by hodgestar** [comment]
Doh. I think that page is good!
