### ISSUE TITLE
Speaker list public in static site, when WAFER_PUBLIC_ATTENDEE_LIST is False

### ISSUE THREAD

**Issue by stefanor** [CTPUG/wafer#289]
https://github.com/CTPUG/wafer/blob/f7f23cbdbcfff353ea83448e8b537551fb525fe2/wafer/users/renderers.py#L13-L14

Not rendering `/users/` anything when `WAFER_PUBLIC_ATTENDEE_LIST` is False means we are likely to fall back to the webserver's directory listing endpoint on `/users/`.

That will show a very ugly list of all the speakers.

medusa doesn't seem to be able to handle http exceptions, which is why we don't try to render `/users/`.

I think the best thing to do would be to just filter the user list down to the approved speaker list, rather than 404ing. Agreed?

**Comment by hodgestar** [comment]
Sounds like the correct approach to me.
