### ISSUE TITLE
Update user profile page

### ISSUE THREAD

**Issue by zoidbergwill** [CTPUG/wafer#315]
I have opinions, and other people have opinions, but no one has ever cared too much.

**Comment by drnlm** [comment]
Could we fill out this issue with a few more details?

**Comment by zoidbergwill** [comment]
I'm not too sure what this was about. 🤔. I think about redesigning the profile detail view. Maybe we can do it with some Bootstrap 4 card stuff.

**Comment by drnlm** [comment]
Any reason not to close this issue?

**Comment by hodgestar** [comment]
The layout and design of the profile page is a bit meh, but I don't think we need to keep a ticket open for it.

**Comment by drnlm** [comment]
Closing
