### ISSUE TITLE
Cancelled talks show up publicly

### ISSUE THREAD

**Issue by baldurmen** [CTPUG/wafer#356]
When a talk is marked as "Cancelled", it shows up on the public talk list page with "C" as a prefix.

This is not the best option since it's very confusing for users that browse that page. It would be best if they could hidden and shown only to registered users with the right accesses.

**Comment by drnlm** [comment]
Cancelled talks remain public by design. It is to prevent published links to talks 404'ing, and to avoid breaking the schedule when a talk is cancelled late in the conference.

If you want the talk to vanish, use one of the other states, such as "Not Accepted".
