### ISSUE TITLE
Update bootstrapto 4beta2

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#385]
We've fallen a bit behind in tracking bootstrap development, so we should update and sort out whatever breaks again.

**Comment by zoidbergwill** [comment]
Django Crispy Forms also needs some work for the latest bootstrap 4 beta, so I might try tackle both at the sprint or before then.

**Comment by stefanor** [comment]
Do we know what is broken in crispy forms?

**Comment by zoidbergwill** [comment]
Mainly need to merge in this gross huge PR: https://github.com/django-crispy-forms/django-crispy-forms/pull/735

**Comment by zoidbergwill** [comment]
But I don't think anything major is broken. It's mostly polish.
