### ISSUE TITLE
Addition of sponsors without needing to redeploy site.

### ISSUE THREAD

**Issue by hodgestar** [CTPUG/wafer#386]
Currently there are a few common tasks that require either writing code, deploying new images or fiddly markup when adding a sponsor:

- [x] Adding a sponsor to the top navigation menu (settings.py change currently).
- [x] Adding a sponsor to the footer (requires base template change and uploading footer version of the logo).
- [x] Adding the sponsor image and link to the sponsor page (requires fiddly markup)
- [ ] All sponsor files are showing for every sponsor in the sponsor edit page (we should probably filter the list so that only files linked to the current sponsor are shown).

This follows on from #213.

**Comment by drnlm** [comment]
With the tagged file support for sponsor files and the automatic footer and block inline templates, what still needs to happen here?

**Comment by hodgestar** [comment]
I think this can be considered done.
