### ISSUE TITLE
Talks can't cross midnight

### ISSUE THREAD

**Issue by stefanor** [CTPUG/wafer#452]
The data model for wafer schedule slots is:
* Day that have a date
* Venue (many:many with Days)
* Slot (many:1 with Venue) has only a time, not a date
* ScheduleItem (many:1 with Slot + Venue)

Because slots are tied to a specific date, a talk can't cross midnight.

The solution here is probably to give Days a start and end datetime, and allow the end to be on a different date. Slots would use datetimes too, and be validated to fit within a Day. It may make sense to rename Day to ScheduleBlock or something.

**Comment by olasd** [comment]
As long as `Slot`s start using `datetime`s instead of having to join them to a `Day` to get one, I'll be happy, I guess. It'll at least reduce the number of silly hax in the volunteer app, as well as in the "schedule in your timezone" stuff that was implemented during DebConf.

**Comment by stefanor** [comment]
Hrm, can this be closed now?

**Comment by drnlm** [comment]
Closing since, with #456, it's possible to have talks cross midnight.

Further enhancements and fixes should be new issues.
