### ISSUE TITLE
License info for Weblate resource

### ISSUE THREAD

**Issue by comradekingu** [CTPUG/wafer#488]
Currently https://hosted.weblate.org/projects/whiskers/#information is missing license info, it just links here.
This can be fixed in https://hosted.weblate.org/settings/whiskers/guide-atom/ and similar for each respective component. Would be better if it said "ISC" and linked to the actual file. My username is https://hosted.weblate.org/user/kingu/ if you want me to do it.

**Comment by drnlm** [comment]
For reference, the correct url is https://hosted.weblate.org/projects/wafer/wafer/#information 

@andrewshadura was this something you setup? Can you update the license?

**Comment by andrewshadura** [comment]
Right, I guess the admin who created the project made a mistake.
Anyway, I have updated the license and added the link to the text.

**Comment by drnlm** [comment]
Thanks
