### ISSUE TITLE
github_username may not be unique

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#52]
As seen recently on pyconza

<stuff snipped>
return UserProfile.objects.get(github_username=github_login).user
<stuff snipped>
MultipleObjectsReturned: get() returned more than one UserProfile -- it returned 2!

And we do indeed have 2 accounts with the same github_username in the database.

Unlike the recent ticket case, it much less clear to me what the right thing to do here is. Taking the one of the matches seems incorrect, since the github_username can be set on an account long after it's been created. It's tempting to force github_username to be unique, although that might cause some surprises.

As a quick fix, I'm inclined to turn this into a straight authentication failure, and leave sorting out the correct solution for later.

**Comment by stefanor** [comment]
There is now a pretty error.
