### ISSUE TITLE
Submitting a talk review via the talk page may update the talk status without creating a revision.

### ISSUE THREAD

**Issue by hodgestar** [CTPUG/wafer#608]
In [TalkReview.form_valid](https://github.com/CTPUG/wafer/blob/6b0cafefff466cb33e92ac4732531f23c9bc26be/wafer/talks/views.py#L234-L237) the talk status is updated if a first review is added and the talk is not yet under review, but no talk revision is created for the update.

This doesn't break anything, but creates a confusing gap in the talk revision audit trail.

**Comment by drnlm** [comment]
Fixed by #626
