### ISSUE TITLE
icalendar 5.0 breaks the tests

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#655]
With icalendar 5.0, the test_ics_view test fails with
```
File "/home/runner/work/wafer/wafer/wafer/schedule/tests/test_views.py", line 1526, in test_ics_view
20
    self.assertEqual(event['dtstart'].params['value'], 'DATE-TIME')
21
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/icalendar/caselessdict.py", line 40, in __getitem__
22
    return super().__getitem__(key.upper())
23
KeyError: 'VALUE'
```

but it works fine with 4.1

There's nothing obvious in the icalendar changelog about this behaviour change, so more investriagtion is needed.

**Comment by hodgestar** [comment]
Odd. What is in `event['dtstart'].params`?

**Comment by drnlm** [comment]
It's contains some metadata about the ical record - the test uses as part of the test that times are exported correctly.
