### ISSUE TITLE
Ask for fediverse / mastodon id in profile page

### ISSUE THREAD

**Issue by pravi** [CTPUG/wafer#661]
Currently the profile asks for homepage, twitter and github. I think adding an option to publish fediverse / mastodon profile/id would be nice.

May be an easy way to add more fields down stream, like debconf23.debconf.org/ use wafer and it'd be good to be highlight username on salsa.debian.org there. When asked on the debconf team channel, it was suggested to ask upstream and doing that downstream is no easy.

**Comment by hodgestar** [comment]
We do support customizing the Django user model, but yes, it's probably a lot of work for downstream sites (one has to add the new user model fields, override the profile form and templates -- probably a bit of a mess).

I'd be slightly more in favour of making the list of external sites included in the user profile configurable somewhere than just adding another site, but I'm not particular sure what that should look like yet.
