### ISSUE TITLE
Improve ticket admin interace

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#719]
The ticket admin interface displays minimal information, which makes tracking down inconsisitencies in the data (due to missed notifications, etc) hard.

Minimal features that seem helpful
a) Counts for the different ticket types
b) Displaying ticket type as a filterable / sortable column in the ticket list

**Comment by hodgestar** [comment]
It would also be good to be able to categorize ticket types somehow so that we could search for "online" tickets or "offline" tickets (and maybe "tutorial" tickets). Perhaps just a tag field on the ticket types table?
