### ISSUE TITLE
Improve error reporting for github authentication failures

### ISSUE THREAD

**Issue by drnlm** [CTPUG/wafer#97]
Quoting from an email I was sent earlier today (after sending out the call for speakers)

> Using social login, I get redirected to github, click authorise, application, page reloads and I get 
> "Unexpected response from github. Authentication failed"
> as the only response.

We hit that code path when we can't get all the information we expect from github, so we can't create the account, but it's not clear to the user what the problem is, so this should be improved.

**Comment by stefanor** [comment]
I think I mostly did this in #142
